Repository joomla/Manual, pull requests merged in 2024-08, with the labels that each got.

#292 Update README to use API link plugin
  README.md
Labels: documentation, Review effort [1-5]: 1

#291 Content plugin events
  docs/building-extensions/plugins/joomla-4-and-5-changes.md
  docs/building-extensions/plugins/plugin-events/content.md
  docs/building-extensions/plugins/plugin-events/index.md
  versioned_docs/version-4.4/building-extensions/plugins/joomla-4-and-5-changes.md
  versioned_docs/version-4.4/building-extensions/plugins/plugin-events/content.md
  versioned_docs/version-4.4/building-extensions/plugins/plugin-events/index.md
  versioned_docs/version-5.1/building-extensions/plugins/joomla-4-and-5-changes.md
  versioned_docs/version-5.1/building-extensions/plugins/plugin-events/content.md
  versioned_docs/version-5.1/building-extensions/plugins/plugin-events/index.md
Labels: documentation, Review effort [1-5]: 3

#295 Adding new joomla development strategy
  docs/development-strategy/_assets/releaseplan.png
  docs/development-strategy/index.md
Labels: documentation, Review effort [1-5]: 1

#297 Add missing .md extension to general-concepts/the-lifecycle
  docs/general-concepts/the-lifecycle.md
  versioned_docs/version-4.4/general-concepts/the-lifecycle.md
  versioned_docs/version-5.0/general-concepts/the-lifecycle.md
  versioned_docs/version-5.1/general-concepts/the-lifecycle.md
Labels: documentation, Review effort [1-5]: 1

#258 [5.2] Deprecated JComponentTitle
  migrations/51-52/new-deprecations.md
Labels: Waiting for Joomla reference PR

#298 [5.2] radio basic deprecate #43860
  migrations/51-52/new-deprecations.md
Labels: documentation, Review effort [1-5]: 1
