Repository joomla/Manual, pull requests merged in 2024-09, with the labels that each got.

#302 modalselect documented, js library folder, small fixes
  docs/building-extensions/components/example-form-component.md
  docs/building-extensions/modules/module-development-tutorial/step9-ajax.md
  docs/general-concepts/forms-fields/standard-fields/_assets/modalselect1.jpg
  docs/general-concepts/forms-fields/standard-fields/_assets/modalselect2.jpg
  docs/general-concepts/forms-fields/standard-fields/_assets/modalselect3.jpg
  docs/general-concepts/forms-fields/standard-fields/index.md
  docs/general-concepts/forms-fields/standard-fields/modalselect.md
  docs/general-concepts/icons.md
  docs/general-concepts/javascript/index.md
  docs/general-concepts/javascript/js-library/core.md
  docs/general-concepts/javascript/js-library/editors.md
  docs/general-concepts/javascript/js-library/index.md
  docs/general-concepts/javascript/js-library/joomla-dialog.md
  docs/general-concepts/javascript/js-library/modal-content-select.md
  versioned_docs/version-4.4/building-extensions/components/example-form-component.md
  versioned_docs/version-4.4/building-extensions/modules/module-development-tutorial/step9-ajax.md
  versioned_docs/version-4.4/general-concepts/icons.md
  versioned_docs/version-4.4/general-concepts/javascript/index.md
  versioned_docs/version-4.4/general-concepts/javascript/js-library/core.md
  versioned_docs/version-4.4/general-concepts/javascript/js-library/editors.md
  versioned_docs/version-4.4/general-concepts/javascript/js-library/index.md
  versioned_docs/version-4.4/general-concepts/javascript/js-library/joomla-dialog.md
  versioned_docs/version-4.4/general-concepts/javascript/js-library/modal-content-select.md
  versioned_docs/version-5.0/building-extensions/components/example-form-component.md
  versioned_docs/version-5.0/building-extensions/modules/module-development-tutorial/step9-ajax.md
  versioned_docs/version-5.0/general-concepts/javascript/index.md
  versioned_docs/version-5.0/general-concepts/javascript/js-library/core.md
  versioned_docs/version-5.0/general-concepts/javascript/js-library/index.md
  versioned_docs/version-5.0/general-concepts/javascript/js-library/joomla-dialog.md
  versioned_docs/version-5.0/general-concepts/javascript/js-library/modal-content-select.md
  versioned_docs/version-5.1/building-extensions/components/example-form-component.md
  versioned_docs/version-5.1/building-extensions/modules/module-development-tutorial/step9-ajax.md
  versioned_docs/version-5.1/general-concepts/icons.md
  versioned_docs/version-5.1/general-concepts/javascript/editors.md
  versioned_docs/version-5.1/general-concepts/javascript/index.md
  versioned_docs/version-5.1/general-concepts/javascript/js-library/core.md
  versioned_docs/version-5.1/general-concepts/javascript/js-library/editors.md
  versioned_docs/version-5.1/general-concepts/javascript/js-library/index.md
  versioned_docs/version-5.1/general-concepts/javascript/js-library/joomla-dialog.md
  versioned_docs/version-5.1/general-concepts/javascript/js-library/modal-content-select.md
Labels: documentation, enhancement, Review effort [1-5]: 3

#306 Added commas
  docs/general-concepts/web-asset-manager.md
  versioned_docs/version-4.4/general-concepts/web-asset-manager.md
  versioned_docs/version-5.0/general-concepts/web-asset-manager.md
  versioned_docs/version-5.1/general-concepts/web-asset-manager.md
Labels: documentation, Review effort [1-5]: 1

#308 adding javascript
  docs/general-concepts/javascript/adding-javascript.md
  docs/general-concepts/javascript/index.md
  docs/general-concepts/javascript/js-library/index.md
  versioned_docs/version-4.4/general-concepts/javascript/adding-javascript.md
  versioned_docs/version-4.4/general-concepts/javascript/index.md
  versioned_docs/version-4.4/general-concepts/javascript/js-library/index.md
  versioned_docs/version-5.1/general-concepts/javascript/adding-javascript.md
  versioned_docs/version-5.1/general-concepts/javascript/index.md
  versioned_docs/version-5.1/general-concepts/javascript/js-library/index.md
Labels: documentation, Review effort [1-5]: 3

#309 Fix display of docusaurus title in README
  README.md
Labels: documentation, Review effort [1-5]: 1

#307 Created a basic library tutorial for everyone to follow and use
  docs/building-extensions/libraries/basic-library.md
  docs/building-extensions/libraries/index.md
  versioned_docs/version-4.4/building-extensions/libraries/basic-library.md
  versioned_docs/version-4.4/building-extensions/libraries/index.md
  versioned_docs/version-5.0/libraries/basic-library.md
  versioned_docs/version-5.0/libraries/index.md
  versioned_docs/version-5.1/libraries/basic-library.md
  versioned_docs/version-5.1/libraries/index.md
Labels: documentation, Review effort [1-5]: 2
