Repository joomla/Manual, pull requests merged in 2024-06, with the labels that each got.

#271 Fix typo index.md
  versioned_docs/version-5.1/index.md
Labels: Bug fix, Review effort [1-5]: 1

#276 Update README.md
  README.md
Labels: documentation, Review effort [1-5]: 2

#277 update links to Joomla APIs
  docs/building-extensions/modules/module-development-tutorial/step7-javascript.md
  docs/building-extensions/modules/module-development-tutorial/step9-ajax.md
  versioned_docs/version-5.1/building-extensions/modules/module-development-tutorial/step7-javascript.md
  versioned_docs/version-5.1/building-extensions/modules/module-development-tutorial/step9-ajax.md
Labels: documentation, Review effort [1-5]: 1
