Repository joomla/Manual, pull requests merged in 2024-11, with the labels that each got.

#243 Chapter about removed db view properties
  migrations/54-60/removed-backward-incompatibility.md
Labels: 6.0, Waiting for Joomla reference PR, Complete

#329 Update compat-plugin.md
  migrations/44-50/compat-plugin.md
Labels: Review effort [1-5]: 1

#328 small typo in 42-43 new-deprecations.md
  migrations/42-43/new-deprecations.md
Labels: Review effort [1-5]: 1

#324 Update icons.md
  docs/general-concepts/icons.md
  versioned_docs/version-4.4/general-concepts/icons.md
  versioned_docs/version-5.2/general-concepts/icons.md
Labels: Review effort [1-5]: 1

#331 Fixing image links #327
  docs/general-concepts/forms-fields/standard-fields/_assets/accessiblemedia/accessiblemedia.jpg
  docs/general-concepts/forms-fields/standard-fields/_assets/calendar/DatePicker1.calendar-en.png
  docs/general-concepts/forms-fields/standard-fields/_assets/calendar/DatePicker2.calendar-en.png
  docs/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-classes-screenshot.png
  docs/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-close-screenshot.png
  docs/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-title-screenshot.png
  docs/general-concepts/forms-fields/standard-fields/accessiblemedia.md
  docs/general-concepts/forms-fields/standard-fields/calendar.md
  docs/general-concepts/forms-fields/standard-fields/note.md
  static/img/screenshots/Params.timezones.jpg
  versioned_docs/version-4.4/general-concepts/forms-fields/standard-fields/_assets/accessiblemedia/accessiblemedia.jpg
  versioned_docs/version-4.4/general-concepts/forms-fields/standard-fields/_assets/calendar/DatePicker1.calendar-en.png
  versioned_docs/version-4.4/general-concepts/forms-fields/standard-fields/_assets/calendar/DatePicker2.calendar-en.png
  versioned_docs/version-4.4/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-classes-screenshot.png
  versioned_docs/version-4.4/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-close-screenshot.png
  versioned_docs/version-4.4/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-title-screenshot.png
  versioned_docs/version-4.4/general-concepts/forms-fields/standard-fields/accessiblemedia.md
  versioned_docs/version-4.4/general-concepts/forms-fields/standard-fields/calendar.md
  versioned_docs/version-4.4/general-concepts/forms-fields/standard-fields/note.md
  versioned_docs/version-5.0/general-concepts/forms-fields/standard-fields/_assets/accessiblemedia/accessiblemedia.jpg
  versioned_docs/version-5.0/general-concepts/forms-fields/standard-fields/_assets/calendar/DatePicker1.calendar-en.png
  versioned_docs/version-5.0/general-concepts/forms-fields/standard-fields/_assets/calendar/DatePicker2.calendar-en.png
  versioned_docs/version-5.0/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-classes-screenshot.png
  versioned_docs/version-5.0/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-close-screenshot.png
  versioned_docs/version-5.0/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-title-screenshot.png
  versioned_docs/version-5.0/general-concepts/forms-fields/standard-fields/accessiblemedia.md
  versioned_docs/version-5.0/general-concepts/forms-fields/standard-fields/calendar.md
  versioned_docs/version-5.0/general-concepts/forms-fields/standard-fields/note.md
  versioned_docs/version-5.1/general-concepts/forms-fields/standard-fields/_assets/accessiblemedia/accessiblemedia.jpg
  versioned_docs/version-5.1/general-concepts/forms-fields/standard-fields/_assets/calendar/DatePicker1.calendar-en.png
  versioned_docs/version-5.1/general-concepts/forms-fields/standard-fields/_assets/calendar/DatePicker2.calendar-en.png
  versioned_docs/version-5.1/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-classes-screenshot.png
  versioned_docs/version-5.1/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-close-screenshot.png
  versioned_docs/version-5.1/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-title-screenshot.png
  versioned_docs/version-5.1/general-concepts/forms-fields/standard-fields/accessiblemedia.md
  versioned_docs/version-5.1/general-concepts/forms-fields/standard-fields/calendar.md
  versioned_docs/version-5.1/general-concepts/forms-fields/standard-fields/note.md
  versioned_docs/version-5.2/general-concepts/forms-fields/standard-fields/_assets/accessiblemedia/accessiblemedia.jpg
  versioned_docs/version-5.2/general-concepts/forms-fields/standard-fields/_assets/calendar/DatePicker1.calendar-en.png
  versioned_docs/version-5.2/general-concepts/forms-fields/standard-fields/_assets/calendar/DatePicker2.calendar-en.png
  versioned_docs/version-5.2/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-classes-screenshot.png
  versioned_docs/version-5.2/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-close-screenshot.png
  versioned_docs/version-5.2/general-concepts/forms-fields/standard-fields/_assets/note/note-form-field-title-screenshot.png
  versioned_docs/version-5.2/general-concepts/forms-fields/standard-fields/accessiblemedia.md
  versioned_docs/version-5.2/general-concepts/forms-fields/standard-fields/calendar.md
  versioned_docs/version-5.2/general-concepts/forms-fields/standard-fields/note.md
Labels: Review effort [1-5]: 1

#322 Form control fields new feature
  docs/general-concepts/forms/manipulating-forms.md
  migrations/52-53/new-features.md
Labels: documentation, Review effort [1-5]: 2, enhancement

#333 Files folder in Media component
  migrations/52-53/new-features.md
Labels: Review effort [1-5]: 1

#342 Underline Links
  src/css/custom.css
Labels: Review effort [1-5]: 1
