Repository joomla/Manual, pull requests merged in 2024-07, with the labels that each got.

#279 Issue: #275, Resolved, Changed the Link color in footer more readable, Issue re…
  docusaurus.config.js
  src/css/custom.css
Labels: Review effort [1-5]: 2, enhancement

#283 Update npm and monkey patch search
  .vscode/settings.json
  package-lock.json
  package.json
  patches/@cmfcmf+docusaurus-search-local+1.2.0.patch
Labels: Bug fix, Review effort [1-5]: 2, enhancement

#280 Plugin for replacing API links
  docs/building-extensions/custom-script/logging-on.md
  docs/building-extensions/modules/module-development-tutorial/step5-config.md
  docs/building-extensions/modules/module-development-tutorial/step7-javascript.md
  docs/building-extensions/modules/module-development-tutorial/step9-ajax.md
  docs/building-extensions/plugins/console-plugin-sqlfile.md
  docs/general-concepts/dashboard.md
  docs/general-concepts/dependency-injection/di-issues.md
  docs/general-concepts/namespaces/joomla-namespace-prefixes.md
  docs/general-concepts/routing/access-component-router-class.md
  docs/general-concepts/user.md
  docusaurus.config.js
  versioned_docs/version-4.4/building-extensions/custom-script/logging-on.md
  versioned_docs/version-4.4/building-extensions/modules/module-development-tutorial/step5-config.md
  versioned_docs/version-4.4/building-extensions/modules/module-development-tutorial/step7-javascript.md
  versioned_docs/version-4.4/building-extensions/modules/module-development-tutorial/step9-ajax.md
  versioned_docs/version-4.4/building-extensions/plugins/console-plugin-sqlfile.md
  versioned_docs/version-4.4/general-concepts/dashboard.md
  versioned_docs/version-4.4/general-concepts/dependency-injection/di-issues.md
  versioned_docs/version-4.4/general-concepts/namespaces/joomla-namespace-prefixes.md
  versioned_docs/version-4.4/general-concepts/routing/access-component-router-class.md
  versioned_docs/version-4.4/general-concepts/user.md
  versioned_docs/version-5.0/building-extensions/custom-script/logging-on.md
  versioned_docs/version-5.0/building-extensions/plugins/console-plugin-sqlfile.md
  versioned_docs/version-5.0/general-concepts/dashboard.md
  versioned_docs/version-5.0/general-concepts/dependency-injection/di-issues.md
  versioned_docs/version-5.0/general-concepts/namespaces/joomla-namespace-prefixes.md
  versioned_docs/version-5.0/general-concepts/routing/access-component-router-class.md
  versioned_docs/version-5.1/building-extensions/custom-script/logging-on.md
  versioned_docs/version-5.1/building-extensions/modules/module-development-tutorial/step5-config.md
  versioned_docs/version-5.1/building-extensions/modules/module-development-tutorial/step7-javascript.md
  versioned_docs/version-5.1/building-extensions/modules/module-development-tutorial/step9-ajax.md
  versioned_docs/version-5.1/building-extensions/plugins/console-plugin-sqlfile.md
  versioned_docs/version-5.1/general-concepts/dashboard.md
  versioned_docs/version-5.1/general-concepts/dependency-injection/di-issues.md
  versioned_docs/version-5.1/general-concepts/namespaces/joomla-namespace-prefixes.md
  versioned_docs/version-5.1/general-concepts/routing/access-component-router-class.md
  versioned_docs/version-5.1/general-concepts/user.md
Labels: documentation, enhancement, Review effort [1-5]: 3

#289 Merging Marco's basic example module documentation
  docs/building-extensions/modules/_assets/mod_example.zip
  docs/building-extensions/modules/basic-module.md
  versioned_docs/version-4.4/building-extensions/modules/_assets/mod_example.zip
  versioned_docs/version-4.4/building-extensions/modules/basic-module.md
  versioned_docs/version-5.1/building-extensions/modules/_assets/mod_example.zip
  versioned_docs/version-5.1/building-extensions/modules/basic-module.md
Labels: documentation, Review effort [1-5]: 2
