Repository joomla/Manual, pull requests merged in 2024-10, with the labels that each got.

#303 Add Bearsampp to list of wamp stacks
  docs/get-started/index.md
  versioned_docs/version-4.4/get-started/index.md
  versioned_docs/version-5.1/get-started/index.md
Labels: documentation, Review effort [1-5]: 1

#288 Media field: allow to select folders
  docs/general-concepts/forms-fields/standard-fields/media.md
  migrations/51-52/new-features.md
Labels: documentation, Review effort [1-5]: 2, enhancement

#318 Removing AbstractView::get()
  migrations/.52-53/new-deprecations.md
Labels: documentation, Review effort [1-5]: 2

#320 Redo #134, Add importmap info to WebAsset manual
  docs/general-concepts/web-asset-manager.md
  versioned_docs/version-5.0/general-concepts/web-asset-manager.md
  versioned_docs/version-5.1/general-concepts/web-asset-manager.md
Labels: documentation, Review effort [1-5]: 2

#290 Auto-start and events information
  docs/general-concepts/guided-tours.md
Labels: documentation, Waiting for Joomla reference PR, Review effort [1-5]: 1

#319 Update radio.md
  docs/general-concepts/forms-fields/standard-fields/radio.md
  versioned_docs/version-5.1/general-concepts/forms-fields/standard-fields/radio.md
Labels: documentation, Review effort [1-5]: 1

#310 Update quicktasklink.md
  docs/building-extensions/components/quicktasklink.md
  versioned_docs/version-5.1/building-extensions/components/quicktasklink.md
Labels: documentation, Review effort [1-5]: 2

#296 Doku change for GMT to UTC change
  migrations/54-60/removed-backward-incompatibility.md
Labels: documentation, Review effort [1-5]: 1

#321 Add deprecate entry for $gmt and $stz in Date class
  migrations/54-60/removed-backward-incompatibility.md
Labels: documentation, Review effort [1-5]: 1, enhancement
