Repository joomla/Manual, pull requests merged in 2024-04, with the labels that each got.

#247 CMS BaseApplication removed
  migrations/54-60/removed-backward-incompatibility.md
Labels: 6.0

#248 CMS Input classes removed
  migrations/54-60/removed-backward-incompatibility.md
Labels: 6.0

#225 Added Database: select, insert, update, delete
  docs/general-concepts/database/delete-data.md
  docs/general-concepts/database/index.md
  docs/general-concepts/database/insert-data.md
  docs/general-concepts/database/query-results.md
  docs/general-concepts/database/select-data.md
  docs/general-concepts/database/update-data.md
  versioned_docs/version-4.4/general-concepts/database/delete-data.md
  versioned_docs/version-4.4/general-concepts/database/index.md
  versioned_docs/version-4.4/general-concepts/database/insert-data.md
  versioned_docs/version-4.4/general-concepts/database/query-results.md
  versioned_docs/version-4.4/general-concepts/database/select-data.md
  versioned_docs/version-4.4/general-concepts/database/update-data.md
  versioned_docs/version-5.0/general-concepts/database/delete-data.md
  versioned_docs/version-5.0/general-concepts/database/index.md
  versioned_docs/version-5.0/general-concepts/database/insert-data.md
  versioned_docs/version-5.0/general-concepts/database/query-results.md
  versioned_docs/version-5.0/general-concepts/database/select-data.md
  versioned_docs/version-5.0/general-concepts/database/update-data.md
Labels: documentation, Need Backport

#236 Additional overview stuff for Web Asset Manager section, plus some tidy-up
  docs/general-concepts/_assets/web-asset-manager-overview.jpg
  docs/general-concepts/_assets/web-asset-manager-overview.odg
  docs/general-concepts/web-asset-manager.md
  versioned_docs/version-4.4/general-concepts/_assets/web-asset-manager-overview.jpg
  versioned_docs/version-4.4/general-concepts/_assets/web-asset-manager-overview.odg
  versioned_docs/version-4.4/general-concepts/web-asset-manager.md
  versioned_docs/version-5.0/general-concepts/_assets/web-asset-manager-overview.jpg
  versioned_docs/version-5.0/general-concepts/_assets/web-asset-manager-overview.odg
  versioned_docs/version-5.0/general-concepts/web-asset-manager.md
Labels: Need Backport

#231 Intro and eclipse
  docs/building-extensions/plugins/_assets/plg_custom_menurule.zip
  docs/building-extensions/plugins/system-plugin-router-rules.md
  docs/building-extensions/plugins/system-plugin.md
  docs/general-concepts/menus-menuitems.md
  docs/general-concepts/routing/access-component-router-class.md
  docs/general-concepts/routing/build.md
  docs/general-concepts/routing/index.md
  docs/general-concepts/routing/parse.md
  docs/general-concepts/routing/router-view.md
  docs/get-started/composer.md
  docs/get-started/ide/eclipse.md
  docs/get-started/ide/index.md
  docs/get-started/ide/phpstorm.md
  docs/get-started/ide/visual-studio-code.md
  docs/get-started/index.md
  docs/get-started/npm.md
  versioned_docs/version-4.4/building-extensions/plugins/_assets/plg_custom_menurule.zip
  versioned_docs/version-4.4/building-extensions/plugins/system-plugin-router-rules.md
  versioned_docs/version-4.4/building-extensions/plugins/system-plugin.md
  versioned_docs/version-4.4/general-concepts/menus-menuitems.md
  versioned_docs/version-4.4/general-concepts/routing/access-component-router-class.md
  versioned_docs/version-4.4/general-concepts/routing/build.md
  versioned_docs/version-4.4/general-concepts/routing/index.md
  versioned_docs/version-4.4/general-concepts/routing/parse.md
  versioned_docs/version-4.4/general-concepts/routing/router-view.md
  versioned_docs/version-4.4/get-started/composer.md
  versioned_docs/version-4.4/get-started/ide/eclipse.md
  versioned_docs/version-4.4/get-started/ide/index.md
  versioned_docs/version-4.4/get-started/ide/phpstorm.md
  versioned_docs/version-4.4/get-started/ide/visual-studio-code.md
  versioned_docs/version-4.4/get-started/index.md
  versioned_docs/version-4.4/get-started/npm.md
  versioned_docs/version-5.0/building-extensions/plugins/_assets/plg_custom_menurule.zip
  versioned_docs/version-5.0/building-extensions/plugins/system-plugin-router-rules.md
  versioned_docs/version-5.0/building-extensions/plugins/system-plugin.md
  versioned_docs/version-5.0/general-concepts/menus-menuitems.md
  versioned_docs/version-5.0/general-concepts/routing/access-component-router-class.md
  versioned_docs/version-5.0/general-concepts/routing/build.md
  versioned_docs/version-5.0/general-concepts/routing/index.md
  versioned_docs/version-5.0/general-concepts/routing/parse.md
  versioned_docs/version-5.0/general-concepts/routing/router-view.md
  versioned_docs/version-5.0/get-started/composer.md
  versioned_docs/version-5.0/get-started/ide/eclipse.md
  versioned_docs/version-5.0/get-started/ide/index.md
  versioned_docs/version-5.0/get-started/ide/phpstorm.md
  versioned_docs/version-5.0/get-started/ide/visual-studio-code.md
  versioned_docs/version-5.0/get-started/index.md
  versioned_docs/version-5.0/get-started/npm.md
Labels: Need Backport

#226 More advanced console plugin example
  docs/building-extensions/components/mvc-pattern.md
  docs/building-extensions/plugins/_assets/plg_console_sqlfile.zip
  docs/building-extensions/plugins/console-plugin-sqlfile.md
  docs/building-extensions/plugins/system-plugin-router-rules.md
  versioned_docs/version-4.4/building-extensions/components/mvc-pattern.md
  versioned_docs/version-4.4/building-extensions/plugins/_assets/plg_console_sqlfile.zip
  versioned_docs/version-4.4/building-extensions/plugins/console-plugin-sqlfile.md
  versioned_docs/version-4.4/building-extensions/plugins/system-plugin-router-rules.md
  versioned_docs/version-5.0/building-extensions/components/mvc-pattern.md
  versioned_docs/version-5.0/building-extensions/plugins/_assets/plg_console_sqlfile.zip
  versioned_docs/version-5.0/building-extensions/plugins/console-plugin-sqlfile.md
  versioned_docs/version-5.0/building-extensions/plugins/system-plugin-router-rules.md
Labels: Need Backport

#235 FTP filesystem plugin example
  docs/building-extensions/plugins/_assets/filesystem-plugin-ftp.md
  docs/building-extensions/plugins/_assets/media-overview.jpg
  docs/building-extensions/plugins/_assets/media-overview.odg
  docs/building-extensions/plugins/_assets/plg_filesystem_ftp.zip
  docs/building-extensions/plugins/_assets/plg_filesystem_restricted.zip
  docs/building-extensions/plugins/_assets/screenshot-filesystem-adapters.png
  docs/building-extensions/plugins/filesystem-plugin-basic.md
  docs/building-extensions/plugins/filesystem-plugin-ftp.md
  versioned_docs/version-4.4/building-extensions/plugins/_assets/media-overview.jpg
  versioned_docs/version-4.4/building-extensions/plugins/_assets/media-overview.odg
  versioned_docs/version-4.4/building-extensions/plugins/_assets/plg_filesystem_ftp.zip
  versioned_docs/version-4.4/building-extensions/plugins/_assets/plg_filesystem_restricted.zip
  versioned_docs/version-4.4/building-extensions/plugins/_assets/screenshot-filesystem-adapters.png
  versioned_docs/version-4.4/building-extensions/plugins/filesystem-plugin-basic.md
  versioned_docs/version-4.4/building-extensions/plugins/filesystem-plugin-ftp.md
  versioned_docs/version-5.1/building-extensions/plugins/_assets/filesystem-plugin-ftp.md
  versioned_docs/version-5.1/building-extensions/plugins/_assets/media-overview.jpg
  versioned_docs/version-5.1/building-extensions/plugins/_assets/media-overview.odg
  versioned_docs/version-5.1/building-extensions/plugins/_assets/plg_filesystem_ftp.zip
  versioned_docs/version-5.1/building-extensions/plugins/_assets/plg_filesystem_restricted.zip
  versioned_docs/version-5.1/building-extensions/plugins/_assets/screenshot-filesystem-adapters.png
  versioned_docs/version-5.1/building-extensions/plugins/filesystem-plugin-basic.md
  versioned_docs/version-5.1/building-extensions/plugins/filesystem-plugin-ftp.md
Labels: Need Backport
