Repository joomla/Manual, pull requests merged in 2025-05, with the labels that each got.

#454 Fixed typos and minor verbal issues in README.md
  README.md
Labels: Review effort 1/5

#462 Update icons.md
  versioned_docs/version-5.3/general-concepts/icons.md
Labels: Review effort 1/5

#422 CMSPlugin: deprecation for registerListeners
  migrations/53-54/new-deprecations.md
Labels: Waiting for Joomla reference PR

#468 migrations/51-52 Remove not-released-yet notice
  migrations/51-52/new-features.md
Labels: Review effort 1/5

#467 migrations/readme - Fixed minor typos and spelling
  migrations/index.md
Labels: Review effort 1/5

#470 Changed images and reworded to explain missing Apply Patch buttons.
  docs/testing/manually/_assets/patch-tester-list.png
  docs/testing/manually/_assets/patch-tester-settings-authentication.png
  docs/testing/manually/patch-tester.md
Labels: Review effort 1/5

#471 migriation/5.4 Add so far merged new features
  migrations/53-54/new-deprecations.md
  migrations/53-54/new-features.md
Labels: Review effort 1/5

#370 Additional documentation for tours: how to create the What's New tour and prepare it for a Joomla release
  docs/general-concepts/guided-tours/create-whatsnewtour.md
  docs/general-concepts/guided-tours/creating-tours.md
  docs/general-concepts/guided-tours/index.md
Labels: documentation, Review effort 2/5

#473 After 5.4.0-alpha1 build added small changes.
  migrations/53-54/compat-plugins.md
  migrations/53-54/new-deprecations.md
  migrations/53-54/new-features.md
Labels: Review effort 1/5

#389 Change input chapter to be moved
  migrations/54-60/compat-plugin.md
Labels: 6.0, Waiting for Joomla reference PR

#459 Remove the static getLogContentTypeParams function
  migrations/54-60/removed-backward-incompatibility.md
Labels: 6.0, Waiting for Joomla reference PR, Review effort 1/5

#475 Update status.md
  docs/general-concepts/forms-fields/standard-fields/status.md
Labels: Review effort 1/5

#477 Unified all headers in migrations section as title case.
  migrations/310-40/index.md
  migrations/310-40/new-deprecations.md
  migrations/310-40/new-features.md
  migrations/310-40/removed-backward-incompatibility.md
  migrations/40-41/index.md
  migrations/40-41/new-deprecations.md
  migrations/40-41/new-features.md
  migrations/40-41/removed-backward-incompatibility.md
  migrations/41-42/index.md
  migrations/41-42/new-deprecations.md
  migrations/41-42/new-features.md
  migrations/41-42/removed-backward-incompatibility.md
  migrations/42-43/index.md
  migrations/42-43/layout-changes.md
  migrations/42-43/new-deprecations.md
  migrations/42-43/new-features.md
  migrations/42-43/removed-backward-incompatibility.md
  migrations/43-44/index.md
  migrations/43-44/new-deprecations.md
  migrations/43-44/new-features.md
  migrations/43-44/removed-backward-incompatibility.md
  migrations/44-50/compat-plugin.md
  migrations/44-50/index.md
  migrations/44-50/new-deprecations.md
  migrations/44-50/new-features.md
  migrations/44-50/removed-backward-incompatibility.md
  migrations/50-51/compat-plugin.md
  migrations/50-51/index.md
  migrations/50-51/new-deprecations.md
  migrations/50-51/new-features.md
  migrations/50-51/removed-backward-incompatibility.md
  migrations/51-52/compat-plugin.md
  migrations/51-52/index.md
  migrations/51-52/new-deprecations.md
  migrations/51-52/new-features.md
  migrations/52-53/compat-plugin.md
  migrations/52-53/index.md
  migrations/52-53/new-deprecations.md
  migrations/52-53/new-features.md
  migrations/53-54/index.md
  migrations/53-54/new-deprecations.md
  migrations/53-54/new-features.md
  migrations/54-60/compat-plugin.md
  migrations/54-60/index.md
  migrations/54-60/new-deprecations.md
  migrations/54-60/new-features.md
  migrations/54-60/removed-backward-incompatibility.md
Labels: Review effort 2/5
