Repository joomla/Manual, pull requests merged in 2025-03, with the labels that each got.

#414 Tab-state script removed
  migrations/54-60/removed-backward-incompatibility.md
Labels: Review effort 1/5

#376 Adding move of CMS filesystem package to compat plugin
  migrations/54-60/removed-backward-incompatibility.md
Labels: Review effort [1-5]: 1

#430 Update index.md (Added more relevant information about IDEs to complete this page.)
  docs/get-started/ide/index.md
Labels: Review effort 1/5

#435 Add allowed and forbidden list to words 2 watch
  docs/user-interface-text/words2watch.md
Labels: Review effort 2/5
