Repository joomla/Manual, pull requests merged in 2025-02, with the labels that each got.

#347 Remove the client id in the model cleanCache function
  migrations/54-60/removed-backward-incompatibility.md
Labels: Review effort [1-5]: 1

#345 Add isCli removal chapter
  migrations/54-60/removed-backward-incompatibility.md
Labels: Review effort [1-5]: 1

#384 Update form-field combo.md
  docs/general-concepts/forms-fields/standard-fields/combo.md
  versioned_docs/version-5.1/general-concepts/forms-fields/standard-fields/combo.md
  versioned_docs/version-5.2/general-concepts/forms-fields/standard-fields/combo.md
Labels: Review effort [1-5]: 1

#383 Revised Manual Testing
  docs/testing/index.md
  docs/testing/manually/_assets/issue-tracker-test-result.png
  docs/testing/manually/_assets/patch-tester-list.png
  docs/testing/manually/_assets/patch-tester-settings-authentication.png
  docs/testing/manually/index.md
  docs/testing/manually/patch-tester.md
  docs/testing/manually/prebuild-packages.md
Labels: Review effort [1-5]: 2

#380 Documentation for removal of CMSObject from core code
  migrations/54-60/removed-backward-incompatibility.md
Labels: Review effort [1-5]: 1

#391 Update software-release-cycle.md
  docs/development-strategy/software-release-cycle.md
Labels: Review effort 1/5

#392 Update backward-compatibility-policy.md
  docs/development-strategy/backward-compatibility-policy.md
Labels: Review effort 1/5

#394 Update visual-studio-code.md
  docs/get-started/ide/visual-studio-code.md
Labels: Review effort 1/5

#393 Revised Technical Requirements for accessibility, clarity and to remo…
  docs/get-started/technical-requirements.md
Labels: Review effort 1/5

#398 Update index.md
  docs/general-concepts/namespaces/index.md
Labels: Review effort 1/5

#399 Update basic-content-plugin.md
  docs/building-extensions/plugins/basic-content-plugin.md
Labels: Review effort 1/5

#397 Update github-joomla-cms.md
  docs/get-started/git/_assets/github-workflow-for-joomla.png
  docs/get-started/git/github-joomla-cms.md
Labels: Review effort 1/5
