Repository joomla/Manual, pull requests merged in 2025-04, with the labels that each got.

#439 Document dependency updates for PHP 8.4
  migrations/52-53/index.md
Labels: Review effort 1/5

#436 Deprecate TYPO3/phar-stream-wrapper
  migrations/52-53/new-deprecations.md
Labels: Review effort 1/5

#437 Removing TYPO3/phar-stream-wrapper
  migrations/54-60/removed-backward-incompatibility.md
Labels: 6.0, Review effort 1/5

#449 expand time.md
  docs/general-concepts/forms-fields/standard-fields/time.md
  versioned_docs/version-5.2/general-concepts/forms-fields/standard-fields/time.md
Labels: Review effort 2/5

#447 Add chapter for buildVotingQuery removal
  migrations/54-60/removed-backward-incompatibility.md
Labels: Review effort 1/5

#452 Remove auto registering stream
  migrations/54-60/removed-backward-incompatibility.md
Labels: Review effort 1/5

#386 Remove LegacyErrorHandlingTrait from CategoryNode & Changelog
  migrations/54-60/removed-backward-incompatibility.md
Labels: Review effort [1-5]: 1

#451 Remove tfa property from login view
  migrations/54-60/removed-backward-incompatibility.md
Labels: Review effort 1/5

#348 Move the JPATH_PLATFORM constant to the compat plugin
  migrations/54-60/compat-plugin.md
Labels: Review effort [1-5]: 1

#364 Deprecations from #40613 added functionality
  migrations/52-53/new-deprecations.md
Labels: Review effort [1-5]: 1

#363 New feature added to batch remove single tag
  migrations/54-60/new-features.md
Labels: Review effort [1-5]: 1

#381 Documentation for deprecation and removal of voku/portable-utf8
  migrations/52-53/new-deprecations.md
  migrations/54-60/removed-backward-incompatibility.md
Labels: 6.0, Waiting for Joomla reference PR, Review effort [1-5]: 1

#353 Capitalization Suggestion
  docs/user-interface-text/capitalisation.md
Labels: Review effort [1-5]: 1

#346 Update removed-backward-incompatibility.md
  migrations/54-60/removed-backward-incompatibility.md
Labels: Review effort [1-5]: 1

#337 Update codestyle.md
  docs/get-started/codestyle.md
  versioned_docs/version-5.2/get-started/codestyle.md
  versioned_docs/version-5.3/get-started/codestyle.md
Labels: Review effort [1-5]: 1

#330 Documenting application routing
  docs/general-concepts/routing/index.md
Labels: Review effort [1-5]: 2

#274 com_ajax Stringable interface
  migrations/52-53/new-features.md
Labels: documentation, Review effort [1-5]: 1, enhancement

#453 Select not click
  versioned_docs/version-5.3/user-interface-text/A-Z.md
Labels: Review effort 1/5
