Repository joomla/Manual, pull requests merged in 2025-09, with the labels that each got.

#512 Migration section for Joomla 6.1
  migrations/60-61/compat-plugin.md
  migrations/60-61/index.md
  migrations/60-61/new-deprecations.md
  migrations/60-61/new-features.md
Labels: Review effort 2/5

#301 CMS Adapter removed
  migrations/54-60/removed-backward-incompatibility.md
Labels: documentation, 6.0, Review effort [1-5]: 1

#460 Removes fetchExtensionCompatibility in UpdateController class
  migrations/54-60/removed-backward-incompatibility.md
Labels: 6.0, Waiting for Joomla reference PR, Review effort 1/5

#522 Migrations/53-54 changes for 5.4.0-beta3
  migrations/53-54/changed-deprecations.md
  migrations/53-54/new-deprecations.md
  migrations/53-54/new-features.md
Labels: Review effort 1/5

#519 Added Date and Date-Time Local Fields
  docs/general-concepts/forms-fields/standard-fields/_assets/date-time-fields.png
  docs/general-concepts/forms-fields/standard-fields/date.md
  docs/general-concepts/forms-fields/standard-fields/datetime.md
  docs/general-concepts/forms-fields/standard-fields/index.md
Labels: Review effort 2/5

#521 Updated headertag and moduletag for J6
  docs/general-concepts/forms-fields/standard-fields/headertag.md
  docs/general-concepts/forms-fields/standard-fields/moduletag.md
Labels: Review effort 1/5

#525 Update joomla-dialog.md
  docs/general-concepts/javascript/js-library/joomla-dialog.md
Labels: Review effort 1/5

#531 implmented/implemented
  docs/building-extensions/daemon/index.md
Labels: Review effort 1/5

#534 Update subform.md
  docs/general-concepts/forms-fields/standard-fields/subform.md
Labels: Review effort 1/5
